# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ca5207fe647ab798687b789d65724c32b11548285161c70f04684af02cd1604d748df3470a10b2deb5f71807c9fbfa1f746092019ae81ff24cfc3d27c61bb0

test:
  secret_key_base: 8c9a8ad66c6d771d420f2a0a5c1427d7ede450202542b8421261176ef3425efc3361617c892a4dcfee2d4d9c199d83c1e2a8478500ff2f2ceaa6f4d96ae15272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
